version: '3.8'
services:
  backend:
    image: ghcr.io/dosenbachgreene/cndamanager:latest
    build: .
    environment:
      - OUTPUT_DIR=/output
    ports:
      - "8000:8000"
    volumes:
      - .:/output
